# Generated by Django 3.1.5 on 2021-01-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20210113_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
