# Generated by Django 3.1.6 on 2021-02-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_auto_20210202_2220"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
    ]
