# Generated by Django 3.1.6 on 2021-02-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_offboarded',
        ),
    ]
