# Generated by Django 3.1.6 on 2021-02-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_remove_profile_is_offboarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
