# Generated by Django 3.1.7 on 2021-04-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_auto_20210205_1752"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="size",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
