# Generated by Django 3.1.7 on 2021-04-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organizations", "0011_organization_size")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("it_manager", "IT Manager"), ("hr", "Human Resources")],
                max_length=50,
                null=True,
                verbose_name="role",
            ),
        )
    ]
