# Generated by Django 3.1.7 on 2021-04-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organizations", "0012_profile_role")]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-20", "1 - 20 employees"),
                            ("21-50", "21 - 50 employees"),
                            ("51-100", "51 - 100 employees"),
                            ("101-200", "101 - 200 employees"),
                            (">200", "> 200 employees"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("it_manager", "IT Manager"),
                            ("hr", "Human Resources"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(model_name="organization", name="size"),
        migrations.RemoveField(model_name="profile", name="role"),
    ]
