# Generated by Django 3.1.7 on 2021-04-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_auto_20210410_1403"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="profile",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="organizations.profile",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_beta_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lead",
            name="organization_size",
            field=models.CharField(
                choices=[
                    ("1-50", "1 - 50 employees"),
                    ("50-200", "50 -200 employees"),
                    ("200-1000", "200 - 1000 employees"),
                    ("> 1000", "> 1000 employees"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("c_level", "C-Level"),
                    ("hr", "Human Resources"),
                    ("sales", "Sales"),
                    ("marketing", "Marketing"),
                    ("product", "Product"),
                    ("engineering", "Engineering"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
