# Generated by Django 3.1.7 on 2021-04-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_auto_20210410_1515"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="organization_size",
            field=models.CharField(
                choices=[
                    ("1-50", "1 - 50 employees"),
                    ("50-200", "50 - 200 employees"),
                    ("200-1000", "200 - 1000 employees"),
                    (">1000", "> 1000 employees"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
