# Generated by Django 3.2 on 2021-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0039_auto_20210225_1121'),
        ('organizations', '0014_auto_20210410_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='app_selection',
            field=models.ManyToManyField(to='integrations.Service'),
        ),
    ]
