# Generated by Django 3.1.7 on 2021-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0015_auto_20210410_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hr", "Human Resources"),
                    ("engineering", "Engineering"),
                    ("marketing", "Marketing"),
                    ("product", "Product"),
                    ("sales", "Sales"),
                    ("c_level", "C-Level"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
