# Generated by Django 3.2 on 2021-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organizations", "0015_lead_app_selection")]

    operations = [
        migrations.RemoveField(model_name="lead", name="email"),
        migrations.RemoveField(model_name="lead", name="first_name"),
        migrations.RemoveField(model_name="lead", name="last_name"),
        migrations.AlterField(
            model_name="lead",
            name="organization_size",
            field=models.CharField(
                choices=[
                    ("gt1", "1 - 50 employees"),
                    ("gt50", "50 - 200 employees"),
                    ("gt200", "200 - 1000 employees"),
                    ("gt1000", "> 1000 employees"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
