# Generated by Django 3.2 on 2021-04-21 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organizations", "0016_auto_20210420_1152")]

    operations = [
        migrations.RemoveField(model_name="profile", name="is_beta_allowed"),
        migrations.AddField(
            model_name="organization",
            name="is_beta_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_onboarded",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="organization_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gt1", "1 - 50 employees"),
                    ("gt50", "50 - 200 employees"),
                    ("gt200", "200 - 1000 employees"),
                    ("gt1000", "> 1000 employees"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT, to="organizations.profile"
            ),
        ),
    ]
