{{- include "app.deployment" (list . "database.deployment") -}}
{{- define "database.deployment" -}}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: registry.hub.docker.com/library/postgres:12.4-alpine
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: {{ .Values.port }}
{{- end -}}
