{{- include "app.deployment" (list . "web.deployment") -}}
{{- define "web.deployment" -}}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          env:
            - name: PORT
              value: "{{ .Values.port }}"
            - name: SERVER_HOST
              value: "server"
            - name: SERVER_PORT
              value: "8000"
          ports:
            - containerPort: {{ .Values.port }}
{{- end -}}
