version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/accounter/server"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/accounter/web"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/accounter/connector"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/e2e-tests"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/accounter/web"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/accounter/server"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/e2e-tests"
    schedule:
      interval: "daily"
