version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/server"
    open-pull-requests-limit: 2
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/web"
    open-pull-requests-limit: 2
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/e2e-tests"
    open-pull-requests-limit: 2
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/e2e-tests"
    schedule:
      interval: "daily"
