version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/accounter/server"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/accounter/web"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/accounter/connector"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/accounter/web"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/accounter/server"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/accounter/connector"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
