version: 2
updates:
  - package-ecosystem: "python"
    directory: "/server"
    schedule:
      interval: "daily"

  - package-ecosystem: "javascript"
    directory: "/web"
    schedule:
      interval: "daily"

  - package-ecosystem: "javascript"
    directory: "/e2e-tests"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/e2e-tests"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/e2e-tests"
    schedule:
      interval: "daily"
