version: "3.8"

services:
  database:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    image: server.development
    build:
      context: ./server
      target: development
    environment:
      - PORT=8000
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=database

        # mock proxy settings
      - USE_MOCK_PROXY=True
      - HTTP_PROXY=mockserver:1080
      - HTTPS_PROXY=mockserver:1080
    env_file:
      - ./server/.env
    volumes:
      - ./server:/code
    depends_on:
      - database

  web:
    image: web.development
    build:
      context: ./web
      target: development
    environment:
      - CI=${CI}
      - PORT=3000
      - SERVER_HOST=server
      - SERVER_PORT=8000
    volumes:
      - ./web:/code
      - /code/node_modules
    stdin_open: true
    depends_on:
      - server