version: "3.8"

services:
  database:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  s3:
    image: adobe/s3mock
    environment:
      - initialBuckets=testbucket
    ports:
      - 9090:9090

  loadbalancer:
    image: loadbalancer
    build: ./accounter/loadbalancer
    volumes:
      - ./accounter/loadbalancer/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./accounter/loadbalancer/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - PORT=8080
      - WEB_HOST=web
      - WEB_PORT=3000
      - SERVER_HOST=server
      - SERVER_PORT=8000
      - S3_HOST=http://s3:9090
      - S3_BUCKET=testbucket
    ports:
      - 8080:8080
    depends_on:
      - web
      - server

  server:
    image: server.development
    build:
      context: ./accounter/server
      target: development
    environment:
      - PORT=8000
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=database
      - POSTGRES_PORT=5432


      - AWS_STORAGE_BUCKET_NAME=testbucket
      - AWS_S3_ENDPOINT_URL=http://s3:9090
      - AWS_DEFAULT_REGION=local

        # mock proxy settings
      - USE_MOCK_PROXY=True
      # - HTTP_PROXY=mockserver:1080
      - HTTPS_PROXY=mockserver:1080
    env_file:
      - ./accounter/server/.env
    volumes:
      - ./accounter/server:/code
    ports:
      - 8000:8000
    depends_on:
      - database
      - s3

  web:
    image: web.development
    build:
      context: ./accounter/web
      target: development
    environment:
      - CI=${CI}
      - PORT=3000
      - SERVER_HOST=server
      - SERVER_PORT=8000
    volumes:
      - ./accounter/web:/code
      - /code/node_modules
    stdin_open: true
    depends_on:
      - server

  mockserver:
    image: mockserver/mockserver:mockserver-5.11.2
    ports:
      - 1080:1080

  e2e:
    build: ./e2e-tests
    environment:
      - LOADBALANCER_HOST=loadbalancer
      - LOADBALANCER_PORT=8080
      - CYPRESS_baseUrl=http://loadbalancer:8080
    working_dir: /e2e
    volumes:
      - ./e2e-tests:/e2e
      - /e2e/node_modules
    depends_on:
      - loadbalancer
      - mockserver
