version: "3.8"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    image: server.development
    build: ./server
    environment:
      - PORT=8000
    volumes:
      - ./server:/code
    ports:
      - "8000:8000"
    depends_on:
      - database

  web:
    image: web.development
    build:
      context: ./web
      target: development
    environment:
      - CI=${CI}
      - PORT=3000
    volumes:
      - ./web:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - server

  e2e:
    build: ./e2e-tests
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:3000
    working_dir: /e2e
    command: npm i @testing-library/cypress
    volumes:
      - ./e2e-tests:/e2e
      - /e2e/node_modules
