version: "3.8"

services:
  web:
    image: web.production
    build:
      target: production

  server:
    image: server.production
    build:
      target: production

  connector:
    image: connector.production
    build:
      target: production
    environment:
      - NODE_ENV=development
