version: "3.8"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  s3:
    image: adobe/s3mock
    environment:
      - initialBuckets=developmentbucket
    ports:
      - 127.0.0.1:9090:9090

  loadbalancer:
    image: loadbalancer
    build: ./accounter/loadbalancer
    volumes:
      - ./accounter/loadbalancer/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./accounter/loadbalancer/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - PORT=8080
      - WEB_HOST=web
      - WEB_PORT=3000
      - SERVER_HOST=server
      - SERVER_PORT=8000
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - web
      - server

  mailserver:
    image: mailhog/mailhog
    ports:
      - 127.0.0.1:8025:8025

  server:
    image: server.development
    build:
      context: ./accounter/server
      target: development
    environment:
      - ENVIRONMENT=development
      - BASE_URL=http://localhost:8080
      - PORT=8000
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=database
      - POSTGRES_PORT=5432

      - CONNECTOR_HOST=connector
      - CONNECTOR_PORT=3000

      - AWS_STORAGE_BUCKET_NAME=developmentbucket
      - AWS_S3_ENDPOINT_URL=http://s3:9090
      - AWS_DEFAULT_REGION=local

      # Env vars only neccessary for dev
      - AWS_S3_CUSTOM_DOMAIN=localhost:9090/developmentbucket
      - AWS_S3_SECURE_URLS=False

      # Email
      - EMAIL_HOST=mailserver
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=False

      # Just used for dev
      - SECRET_KEY=-7k-e#5^w@00zsxi$$0+i!n$$&4w#m-i@x4+i@(lp$$e1q3m#0p$$-
    env_file:
      - ./accounter/server/.env
    volumes:
      - ./accounter/server:/code
      - shared-graphql:/code/shared-graphql
    depends_on:
      - database
      - s3
      - connector

  connector:
    image: connector.development
    build:
      context: ./accounter/connector
      target: development
    volumes:
      - ./accounter/connector:/code
      - /code/node_modules
    env_file:
      - ./accounter/connector/.env
    environment:
      - CI=${CI}
      - PORT=3000

      - SLACK_STATE_SECRET=some-secret

      # Dev only
      - ENCRYPTION_KEY=my_32_chars_encryption_key_12345

  web:
    image: web.development
    build:
      context: ./accounter/web
      target: development
    environment:
      - CI=${CI}
      - PORT=3000
      - SERVER_HOST=server
      - SERVER_PORT=8000
    volumes:
      - ./accounter/web:/code
      - shared-graphql:/code/shared-graphql
      - /code/node_modules
    stdin_open: true
    depends_on:
      - server

  e2e:
    build: ./e2e-tests
    # https://playwright.dev/docs/ci#docker
    image: mcr.microsoft.com/playwright:focal
    ipc: host
    volumes:
      - ./e2e-tests:/code
      - /code/node_modules
    depends_on:
      - loadbalancer
    environment:
      - LOADBALANCER_HOST=loadbalancer
      - LOADBALANCER_PORT=8080
    

volumes:
  shared-graphql:
