version: "3.8"

services:
  database:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  loadbalancer:
    image: loadbalancer
    build: ./loadbalancer
    volumes:
      - ./loadbalancer/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./loadbalancer/docker-entrypoint.sh /docker-entrypoint.sh
    environment:
      - WEB_HOST=web
      - WEB_PORT=3000
      - SERVER_HOST=server
      - SERVER_PORT=8000
    ports:
      - 8080:8080
    depends_on:
      - web
      - server

  server:
    image: server.development
    build:
      context: ./server
      target: development
    environment:
      - PORT=8000
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=database
    volumes:
      - ./server:/code
    depends_on:
      - database

  web:
    image: web.development
    build:
      context: ./web
      target: development
    environment:
      - CI=${CI}
      - PORT=3000
    volumes:
      - ./web:/code
      - /code/node_modules
    stdin_open: true
    depends_on:
      - server

  e2e:
    build: ./e2e-tests
    depends_on:
      - loadbalancer
    environment:
      - CYPRESS_baseUrl=http://loadbalancer:8080
    working_dir: /e2e
    command: npm i @testing-library/cypress
    volumes:
      - ./e2e-tests:/e2e
      - /e2e/node_modules
