apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: accounter
build:
  artifacts:
    - image: reverse-proxy
      context: loadbalancer
      docker:
        dockerfile: Dockerfile
    - image: server.development
      context: server
      docker:
        dockerfile: Dockerfile
    - image: web.development
      context: web
      docker:
        dockerfile: Dockerfile

deploy:
  kubeContext: minikube
  kubectl:
    manifests:
    - k8s/database-credentials.yaml
  helm:
    releases:
        # replace skipBuildDependencies to prevent build loop with helm
      - name: web
        chartPath: web/helm
        skipBuildDependencies: true
        artifactOverrides:
          image: web.development

      - name: server
        chartPath: server/helm
        skipBuildDependencies: true
        artifactOverrides:
          image: server.development

      - name: loadbalancer
        chartPath: loadbalancer/helm
        skipBuildDependencies: true
        artifactOverrides:
          image: reverse-proxy

      - name: database
        chartPath: database/dev/helm
        skipBuildDependencies: true

      - name: mockserver
        chartPath: mockserver/helm
        skipBuildDependencies: true


profiles:
  - name: CI
    patches:
      - op: replace
        path: /deploy/helm/releases/0/skipBuildDependencies
        value: false
      - op: replace
        path: /deploy/helm/releases/1/skipBuildDependencies
        value: false
      - op: replace
        path: /deploy/helm/releases/2/skipBuildDependencies
        value: false
      - op: replace
        path: /deploy/helm/releases/3/skipBuildDependencies
        value: false
      - op: replace
        path: /deploy/helm/releases/4/skipBuildDependencies
        value: false

  - name: production
    patches:
      - op: add
        path: /build/artifacts/-
        value:
            image: server.production
            context: server
            docker:
              dockerfile: Dockerfile.production
            requires:
              - image: server.development
                alias: DEVELOPMENT_IMAGE
      - op: add
        path: /build/artifacts/-
        value:
            image: web.production
            context: web
            docker:
              dockerfile: Dockerfile.production
            requires:
              - image: web.development
                alias: DEVELOPMENT_IMAGE
      - op: replace
        path: /deploy/helm/releases/0/skipBuildDependencies
        value: false
      - op: replace
        path: /deploy/helm/releases/1/skipBuildDependencies
        value: false
      - op: replace
        path: /deploy/helm/releases/2/skipBuildDependencies
        value: false
      - op: replace
        path: /deploy/helm/releases/3/skipBuildDependencies
        value: false
      - op: replace
        path: /deploy/helm/releases/4/skipBuildDependencies
        value: false
        
    deploy:
      kubeContext: do-ams3-accounter
      kubectl:
        manifests:
        - k8s/database-credentials.yaml
      helm:
        releases:
          - name: web
            chartPath: web/helm
            artifactOverrides:
              image: web.production
          - name: server
            chartPath: server/helm
            artifactOverrides:
              image: server.production
          - name: loadbalancer
            chartPath: loadbalancer/helm
            artifactOverrides:
              image: reverse-proxy
          - name: database
            chartPath: database/prod/helm
