apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: accounter
build:
  artifacts:
  - image: reverse-proxy
    context: loadbalancer
    docker:
      dockerfile: Dockerfile
  - image: server
    context: server
    docker:
      dockerfile: Dockerfile
  - image: web
    context: web
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - loadbalancer/k8s.yaml
    - server/k8s.yaml
    - web/k8s.yml
    - k8s/registry-secret.yaml

# profiles:
# - name: development
#   activation:
#     - command: dev
#   deploy:
#     kubectl:
#       manifests:
#       - database/k8s.yaml
#       - loadbalancer/k8s.yaml
#       - server/k8s.yaml
#       - web/k8s.yml