apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: accounter
build:
  artifacts:
    - image: reverse-proxy
      context: loadbalancer
      docker:
        dockerfile: Dockerfile
    - image: server.development
      context: server
      docker:
        dockerfile: Dockerfile
    - image: web.development
      context: web
      docker:
        dockerfile: Dockerfile

profiles:
  - name: development
    activation:
      - command: dev
    deploy:
      kubeContext: minikube
      helm:
        releases:
          - name: web
            chartPath: web/helm
            skipBuildDependencies: true
            artifactOverrides:
              image: web.development

          - name: server
            chartPath: server/helm
            skipBuildDependencies: true
            artifactOverrides:
              image: server.development

          - name: loadbalancer
            chartPath: loadbalancer/helm
            skipBuildDependencies: true
            artifactOverrides:
              image: reverse-proxy

          - name: database
            chartPath: database/dev/helm
            skipBuildDependencies: true

  - name: production
    activation:
      - command: run
    patches:
      - op: add
        path: /build/artifacts/-
        value:
            image: server.production
            context: server
            docker:
              dockerfile: Dockerfile.production
            requires:
              - image: server.development
                alias: DEVELOPMENT_IMAGE
      - op: add
        path: /build/artifacts/-
        value:
            image: web.production
            context: web
            docker:
              dockerfile: Dockerfile.production
            requires:
              - image: web.development
                alias: DEVELOPMENT_IMAGE
    deploy:
      kubeContext: do-ams3-accounter
      helm:
        releases:
          - name: web
            chartPath: web/helm
            artifactOverrides:
              image: web.production
          - name: server
            chartPath: server/helm
            artifactOverrides:
              image: server.production
          - name: loadbalancer
            chartPath: loadbalancer/helm
            artifactOverrides:
              image: reverse-proxy
          - name: database
            chartPath: database/prod/helm
