# Generated by Django 3.1.3 on 2020-11-27 19:00

import os.path

from django.core.files import File
from django.db import migrations

current_path = os.path.abspath(os.path.dirname(__file__))


def add_services(apps, schema_editor):
    Service = apps.get_model("integrations", "Service")
    service = Service.objects.create(name="SLACK")
    with open(
        os.path.join(current_path, "./0002_add_slack_service_slack_logo.svg"), "rb"
    ) as logo:
        service.logo.save("slack.svg", File(logo), save=True)
    service.save()


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_services),
    ]
