# Generated by Django 3.1.3 on 2020-11-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_service_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="data",
            new_name="state_store",
        ),
    ]
