# Generated by Django 3.1.5 on 2021-01-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_slackintegration_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackintegration',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
