# Generated by Django 3.1.5 on 2021-01-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_auto_20210118_1711"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackaccount",
            name="email",
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slackaccount",
            name="username",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
