# Generated by Django 3.1.5 on 2021-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_auto_20210124_1254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackaccount",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
