# Generated by Django 3.1.5 on 2021-01-24 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0010_auto_20210124_1724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackaccount",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="accounts",
                to="integrations.slackintegration",
            ),
        ),
    ]
