# Generated by Django 3.1.5 on 2021-01-25 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_slackintegration_last_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackaccount',
            name='last_refresh',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
