# Generated by Django 3.1.5 on 2021-01-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_slackaccount_last_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackaccount',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
