# Generated by Django 3.1.5 on 2021-01-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_slackaccount_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='state_store',
        ),
    ]
