# Generated by Django 3.1.6 on 2021-02-02 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_auto_20210202_2220"),
        ("integrations", "0019_auto_20210202_1845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackaccount",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="integrations.slackintegration",
            ),
        ),
        migrations.AlterField(
            model_name="slackaccount",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="organizations.profile"
            ),
        ),
        migrations.AlterField(
            model_name="slackintegration",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
    ]
