# Generated by Django 3.1.6 on 2021-02-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0020_auto_20210202_2220"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackaccount",
            name="role",
            field=models.CharField(
                choices=[("USER", "User"), ("ADMIN", "Admin"), ("OWNER", "Owner")],
                default="USER",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
