# Generated by Django 3.1.6 on 2021-02-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20210202_2220'),
        ('integrations', '0021_slackaccount_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlackAccount',
            new_name='Account',
        ),
    ]
