# Generated by Django 3.1.6 on 2021-02-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0024_integration_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="integrations.service"
            ),
        ),
    ]
