# Generated by Django 3.1.6 on 2021-02-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0028_integration_management_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
