# Generated by Django 3.1.6 on 2021-02-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0029_account_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='has_valid_token',
            field=models.BooleanField(default=True),
        ),
    ]
