# Generated by Django 3.1.6 on 2021-02-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0033_integration_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                choices=[("SLACK", "Slack"), ("Google", "Google"), ("Zoom", "Zoom")],
                max_length=50,
                unique=True,
                verbose_name="Type",
            ),
        ),
    ]
