# Generated by Django 3.1.6 on 2021-02-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0035_add_zoom_service_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                choices=[
                    ("SLACK", "Slack"),
                    ("Google", "Google"),
                    ("Zoom", "Zoom"),
                    ("GitHub", "GitHub"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Type",
            ),
        ),
    ]
