# Generated by Django 3.1.7 on 2021-02-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_auto_20210205_1752"),
        ("integrations", "0037_add_github_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="organizations.profile",
            ),
        )
    ]
