# Generated by Django 3.1.7 on 2021-02-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_auto_20210205_1752"),
        ("integrations", "0038_auto_20210223_1201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrations",
                to="organizations.organization",
            ),
        )
    ]
