# Generated by Django 3.2 on 2021-04-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0039_auto_20210225_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo_large',
            field=models.FileField(default='', upload_to='services/logos_large'),
            preserve_default=False,
        ),
    ]
