# Generated by Django 3.1.3 on 2020-11-27 19:00

import os.path

from django.db import migrations

current_path = os.path.abspath(os.path.dirname(__file__))


def fix_slack_service_name(apps, schema_editor):
    Service = apps.get_model("integrations", "Service")
    slack_service = Service.objects.get(name="SLACK")
    slack_service.name = "Slack"
    slack_service.save()


class Migration(migrations.Migration):

    dependencies = [("integrations", "0043_alter_service_name")]

    operations = [migrations.RunPython(fix_slack_service_name)]
