kind: Service
apiVersion: v1
metadata:
 name: {{ .Chart.Name }}
spec:
 ports:
 - port: 5432
   targetPort: 25060
---
kind: Endpoints
apiVersion: v1
metadata:
 name: {{ .Chart.Name }}
subsets:
 - addresses:
     - ip: 10.110.0.4
   ports:
     - port: 25060

