# Generated by Django 3.1.3 on 2020-11-28 18:25

from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_add_slack_service"),
    ]

    operations = [
        HStoreExtension(),
    ]
