# Generated by Django 3.1.3 on 2020-11-28 18:31

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_add_hstore_to_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
