# Generated by Django 3.1.3 on 2020-11-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_auto_20201122_2203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="logo",
            field=models.FileField(upload_to="services/logos"),
        ),
    ]
