# Generated by Django 3.1.3 on 2020-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_auto_20201129_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackintegration',
            name='token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
