apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: app.accounter.io
    http:
      paths:
      - backend:
          serviceName: loadbalancer
          servicePort: 8080