apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: eu.gcr.io/accounter-291508/server:latest
  labels:
    cloud.googleapis.com/location: europe-west1
  name: accounter-server
  namespace: "999814452385"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1000"
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: accounter-291508:us-central1:accounter-database
    spec:
      containerConcurrency: 80
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_URL
              value: /cloudsql/accounter-291508:us-central1:accounter-database
          image: eu.gcr.io/accounter-291508/server:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
      serviceAccountName: 999814452385-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
