ARG DEVELOPMENT_IMAGE

FROM $DEVELOPMENT_IMAGE as development

FROM python:3.9.1 as production
ENV PYTHONUNBUFFERED True
ENV PORT=8000
ENV DEBUG=False
RUN mkdir /code
WORKDIR /code
COPY --from=development /code/requirements /code/requirements
RUN pip install -r requirements/production.txt 
RUN pip install daphne
COPY --from=development /code /code
WORKDIR /code
ENTRYPOINT ["./docker-entrypoint.sh"]
CMD daphne -b 0.0.0.0 -p $PORT config.asgi:application
