apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:3000
    - port: 8000
  type: ClusterIP
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      imagePullSecrets:
        - name: registry-accounter
      containers:
        - name: server
          image: server
          env:
            - name: PORT
              value: "8000"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_URL
              value: "database"
            - name: SLACK_CLIENT_ID
              value: ""
            - name: SLACK_CLIENT_SECRET
              value: ""
          ports:
            - containerPort: 8000