apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  ports:
    - port: 8080
  type: LoadBalancer
  selector:
    app: reverse-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      imagePullSecrets:
        - name: registry-accounter
      containers:
        - name: reverse-proxy
          image: reverse-proxy
          env:
            - name: PORT
              value: "8080"
            - name: PROTOCOL
              value: "http"
            - name: WEB_HOST
              value: "web"
            - name: WEB_PORT
              value: "3000"
            - name: SERVER_HOST
              value: "server"
            - name: SERVER_PORT
              value: "8000"
          ports:
            - containerPort: 8080