{{- include "app.deployment" (list . "server.deployment") -}}
{{- define "server.deployment" -}}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          env:
            - name: PORT
              value: "{{ .Values.port }}"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
            - name: POSTGRES_URL
              value: "database"
            - name: SLACK_CLIENT_ID
              value: ""
            - name: SLACK_CLIENT_SECRET
              value: ""
            - name: POSTGRES_SSL
              value: "True"
          ports:
            - containerPort: {{ .Values.port }}
{{- end -}}
