name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  IMAGE_REGISTRY_TAG_WEB: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/web:${{ github.sha }}
  IMAGE_REGISTRY_TAG_SERVER: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/server:${{ github.sha }}
  IMAGE_REGISTRY_TAG_LOADBALANCER: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/loadbalancer:${{ github.sha }}

jobs:
  health-checks:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: create .env
        run: cp server/.env.example server/.env

      - name: pull dependency images
        run: docker-compose pull

      - name: build
        run: docker-compose build

      - name: lint
        run: |
          docker-compose run --no-deps --entrypoint /usr/bin/env server flake8 accounter
          docker-compose run --no-deps --entrypoint ./dev-setup.sh web npm run lint

      - name: typechecking
        run: |
          docker-compose run --no-deps --entrypoint ./dev-setup.sh web npm run typecheck
          docker-compose run --no-deps --entrypoint /usr/bin/env server pyright

      - name: unit tests
        run: |
          docker-compose run --no-deps --entrypoint ./dev-setup.sh web npm t -- --coverage
          docker-compose run --entrypoint /usr/bin/env server coverage run --source='.' manage.py test
          docker-compose run --no-deps --entrypoint /usr/bin/env server coverage xml

      - name: report coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: web, server
          fail_ci_if_error: true

      - name: check migrations
        run: docker-compose -f docker-compose.yml run --entrypoint /usr/bin/env server python manage.py makemigrations --check

      - name: end-to-end tests production build
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml up --build --exit-code-from e2e

      - name: prepare cloud run manifests
        if: github.ref == 'refs/heads/master'
        run: |
          envsubst '${GITHUB_SHA}' < server/cloudrun.template.yaml > server/cloudrun.yaml
          envsubst '${GITHUB_SHA}' < web/cloudrun.template.yaml > web/cloudrun.yaml
          envsubst '${GITHUB_SHA}' < loadbalancer/cloudrun.template.yaml > loadbalancer/cloudrun.yaml

      - name: django deployment check
        if: github.ref == 'refs/heads/master'
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml run server ./manage.py check --deploy

      - name: Login to google cloud run
        if: github.ref == 'refs/heads/master'
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "312.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: prepare image deployments
        if: github.ref == 'refs/heads/master'
        run: gcloud auth configure-docker

      - name: deploy images to google container registry
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag server.production $IMAGE_REGISTRY_TAG_SERVER
          docker tag web.production $IMAGE_REGISTRY_TAG_WEB
          docker tag loadbalancer $IMAGE_REGISTRY_TAG_LOADBALANCER
          docker push $IMAGE_REGISTRY_TAG_SERVER
          docker push $IMAGE_REGISTRY_TAG_WEB
          docker push $IMAGE_REGISTRY_TAG_LOADBALANCER

      - name: deploy server to production
        if: github.ref == 'refs/heads/master'
        uses: google-github-actions/deploy-cloudrun@main
        env:
          GCLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }} # due to bug, can be removed when using action verson > 0.1.3
        with:
          region: europe-west1
          metadata: ./server/cloudrun.yaml

      - name: deploy web to production
        if: github.ref == 'refs/heads/master'
        uses: google-github-actions/deploy-cloudrun@main
        env:
          GCLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }} # due to bug, can be removed when using action verson > 0.1.3
        with:
          region: europe-west1
          metadata: ./web/cloudrun.yaml

      - name: deploy loadbalancer to production
        if: github.ref == 'refs/heads/master'
        uses: google-github-actions/deploy-cloudrun@main
        env:
          GCLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }} # due to bug, can be removed when using action verson > 0.1.3
        with:
          region: europe-west1
          metadata: ./loadbalancer/cloudrun.yaml
