name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  IMAGE_REGISTRY_TAG_WEB: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/web
  IMAGE_REGISTRY_TAG_SERVER: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/server

jobs:
  health-checks:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: pull dependency images
        run: docker-compose pull
      - name: build
        run: docker-compose build
      - name: linting server
        run: docker-compose run --no-deps --entrypoint python server -m pylint accounter
      - name: linting web
        run: docker-compose run --no-deps web npm run lint
      - name: typechecking web
        run: docker-compose run --no-deps web npm run typecheck
      - name: unit tests web
        run: docker-compose run --no-deps web npm t -- --coverage
      - name: report coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: web
          fail_ci_if_error: true
      - name: end-to-end tests production build
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml up --build --exit-code-from e2e

      - name: django deployment check
        if: github.ref == 'refs/heads/master'
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml run server ./manage.py check --deploy

      - name: Login to google cloud run
        if: github.ref == 'refs/heads/master'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        with:
          version: "312.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: prepare image deployments
        if: github.ref == 'refs/heads/master'
        run: gcloud auth configure-docker

      - name: deploy images to google container registry
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag web.production $IMAGE_REGISTRY_TAG_WEB
          docker tag server.production $IMAGE_REGISTRY_TAG_SERVER
          docker push $IMAGE_REGISTRY_TAG_WEB
          docker push $IMAGE_REGISTRY_TAG_SERVER

      - name: deploy web to production
        if: github.ref == 'refs/heads/master'
        uses: GoogleCloudPlatform/github-actions/deploy-cloudrun@0.1.3
        env:
          GCLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }} # due to bug, can be removed when using action verson > 0.1.3
        with:
          region: europe-west1
          metadata: ./web/cloudrun.yaml

      - name: deploy server to production
        if: github.ref == 'refs/heads/master'
        uses: GoogleCloudPlatform/github-actions/deploy-cloudrun@0.1.3
        env:
          GCLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }} # due to bug, can be removed when using action verson > 0.1.3
        with:
          region: europe-west1
          metadata: ./server/cloudrun.yaml
