name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  IMAGE_REGISTRY_TAG_WEB: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/web
  TIMESTAMP: $(date --iso-8601=ns)

jobs:
  health-checks:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: pull dependency images
        run: docker-compose pull
      - name: build
        run: docker-compose build
      - name: linting server
        run: docker-compose run --no-deps server pylint accounter
      - name: linting web
        run: docker-compose run --no-deps web npm run lint
      - name: typechecking web
        run: docker-compose run --no-deps web npm run typecheck
      - name: unit tests web
        run: docker-compose run --no-deps web npm t -- --coverage
      - name: report coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: web
          fail_ci_if_error: true
      - name: end-to-end tests production build
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml up --no-deps --build --exit-code-from e2e web e2e

      - name: Login to google cloud run
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        with:
          version: "312.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: prepare image deployment
        run: gcloud auth configure-docker

      - name: deploy image to google container registry
        run: |
          docker tag web.production $IMAGE_REGISTRY_TAG_WEB:${TIMESTAMP}
          docker push $IMAGE_REGISTRY_TAG_WEB:${TIMESTAMP}
      - name: deploy image to production
        uses: GoogleCloudPlatform/github-actions/deploy-cloudrun@0.1.3
        with:
          image: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/web:${TIMESTAMP}
          service: accounter-web
          region: europe-west1
          env_vars: TIMESTAMP=$TIMESTAMP
        env:
          GCLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }} # due to bug, can be removed when using action verson > 0.1.3
          TIMESTAMP: ${TIMESTAMP}
