name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  health-checks:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: pull dependency images
        run: docker-compose pull
      - name: docker cache
        uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: build
        run: docker-compose build
      - name: linting server
        run: docker-compose run server pylint accounter
      - name: linting web
        run: docker-compose run web npm run lint
      - name: typechecking web
        run: docker-compose run web npm run typecheck
      - name: unit tests web
        run: docker-compose run web npm t -- --coverage
      - name: report coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: web
          fail_ci_if_error: true
      - name: end-to-end tests production build
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml up --build --exit-code-from e2e
