name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  E2E:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up --exit-code-from e2e
