name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting
        run: docker-compose run web npm run lint
      - name: Typechecking
        run: docker-compose run web npm run typecheck
      - name: End-to-end tests on production build
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml up --build --exit-code-from e2e
