apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: accounter-web
spec:
  template:
    spec:
      containers:
        - env:
            - name: SERVER_URL
              value: https://accounter-server-benpx3qpfa-ew.a.run.app
            - name: SERVER_PORT
              value: "443"
          image: eu.gcr.io/accounter-291508/web:${GITHUB_SHA}
