apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations: {}
  labels:
    cloud.googleapis.com/location: europe-west1
  name: accounter-web
  namespace: "999814452385"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1000"
    spec:
      containerConcurrency: 80
      containers:
        - image: eu.gcr.io/accounter-291508/web:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
