apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: registry-accounter
      containers:
        - name: web
          image: web
          env:
            - name: PORT
              value: "3000"
            - name: SERVER_HOST
              value: "server"
            - name: SERVER_PORT
              value: "8000"
          ports:
            - containerPort: 3000
